# Generated by Django 4.2.2 on 2023-06-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nb_players',
            field=models.IntegerField(),
        ),
    ]
