# Generated by Django 4.2.2 on 2023-06-20 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitTest', '0002_alter_game_nb_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nb_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
